obj-m+=hello.o
 
all:
		make -C /home/dan/buildroot/build/build/linux-headers-rel_imx_4.1.15_2.0.0_ga M=$(PWD) modules
clean:
		make -C /home/dan/buildroot/build/build/linux-headers-rel_imx_4.1.15_2.0.0_ga M=$(PWD) modules